# Generated by Django 4.2 on 2023-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ditto/'),
        ),
    ]
