# Generated by Django 4.2.1 on 2023-05-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditto', '0002_alter_canvasimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasimg',
            name='image',
        ),
        migrations.AddField(
            model_name='canvasimg',
            name='col',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='canvasimg',
            name='prompt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='canvasimg',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
