# Generated by Django 4.2.1 on 2023-05-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditto', '0003_remove_canvasimg_image_canvasimg_col_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('canvas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='ditto.canvasimg')),
            ],
        ),
    ]
