# Generated by Django 4.2.1 on 2023-05-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditto', '0004_inferencequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencequeue',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
